=== Data partitioning
The curated data in the *integration stage* S3 bucket is partitioned by *reading type, year, month, day, hour*, as follows:

`s3://IntegrationBucket/reading_type=<reading_type_value>/year=<year>/month=<month>/day=<day>/hour=<hour>/<meter-data-file-in-parquet-format>`

You can find all meter reads for the hour of a day on the lowest level of the partition tree. To optimize query performance, the data is stored in a column-based file format (Parquet).

=== Late-arriving data
The data lake handles late-arriving meter reads, will be detected as soon as the data reaches the *staging stage*. If a late read is detected an event will be send to Amazon EventBridge. The ETL pipeline takes care of moving the late read to the correct partition, and makes sure that data is still stored in an optimized way.

=== Data Formats
*Inbound format*

The input meter-data format is variable and can be adjusted as described in the section <<Customize this Quick Start,'Customize this Quick Start'>>. The sample input data format of the https://github.com/aws-quickstart/quickstart-aws-utility-meter-data-generator[Meter Data Generator] looks like the following:


[cols="1,1,1", options="header"]
.Inbound schema
|===
|Field
|Type
|Format
|Description

|time|timestamp|yyyy-MM-dd HH:mm:ss.SSSSSSS|The timestamp the read reaches the source system
|reading_time|timestamp|yyyy-MM-dd HH:mm:ss.SSSSSSS|The timestamp of the actual read
|device_id|string|7a044be7-2f1e-3bf1-aa86-b8b1b9064f19|uuid
|measure_name|string|
|load|double|0.000|Load, unit: A
|crrnt|double|0.000|Current, unit: A
|pf|double|0.000|Power Factor, between 0 and 1
|kva|double|0.000|Volt Ampere, unit: VA
|kw|double|0.000|Kilowatt, unit: kW
|vltg|double|0.000|Voltage, unit V
|===

*Integrated format*

Data is stored in the following format in the *integration stage*.

[cols="1,1,1", options="header"]
.Integration schema
|===
|Field
|Type
|Format

|meter_id           |String     |
|reading_value      |Double     |0.000
|reading_date_time  |Timestamp  |yyyy-MM-dd HH:mm:ss.SSS
|reading_type       |String     |load, crrnt, pf, kva, kw, vltg
|unit               |String     |
|obis_code          |String     |
|phase              |String     |
|reading_source     |String     |
|reading_type       |String (Partitioned)   |
|year               |String (Partitioned)   |
|month              |String (Partitioned)   |
|day                |String (Partitioned)   |
|hour               |String (Partitioned)   |
|===



=== API
TBD