=== Launch the QuickStart

NOTE: You are responsible for the cost of the AWS services used while running this QuickStart reference deployment. There is no additional cost for using this Quick Start. For full details, see the pricing pages for each AWS service used by this Quick Start. Prices are subject to change.

. Sign in to your AWS account, and launch the following AWS CloudFormation template.

.Deployment Link
****
TODO update link

https://fwd.aws/5Pj8e[Deploy {partner-product-name} on AWS^]
****

The deployment takes about {deployment_time} to complete.

[start=2]
. Check the AWS Region that’s displayed in the upper-right corner of the navigation bar, and change it if necessary. This is where the network infrastructure for {partner-product-name} is built. The template is launched in the {default_deployment_region} Region by default.

[start=3]
. On the *Create stack* page, keep the default setting for the template URL, and then choose *Next*.
. On the *Specify stack details* page, change the stack name if needed. Review the parameters for the template. Provide values for the parameters that require input. For all other parameters, review the default settings and customize them as necessary. For details on each parameter, see the link:#_parameter_reference[Parameter reference] section of this guide.
